import {
  lucideActivity,
  lucideArrowUpDown,
  lucideCalendarDays,
  lucideClock,
  lucideDumbbell,
  lucideHash,
  lucideHistory,
  lucideLayoutDashboard,
  lucidePlus,
  lucideSave,
  lucideTable,
  lucideTrendingUp,
} from '@ng-icons/lucide';

export const appIcons = {
  navDashboard: lucideLayoutDashboard,
  navExercises: lucideDumbbell,
  sectionToday: lucideActivity,
  sectionWeek: lucideCalendarDays,
  sectionTrends: lucideTrendingUp,
  sectionRecent: lucideHistory,
  sectionTable: lucideTable,
  metricDuration: lucideClock,
  metricReps: lucideHash,
  metricWeightedReps: lucideDumbbell,
  actionSave: lucideSave,
  actionReorder: lucideArrowUpDown,
  actionAdd: lucidePlus,
};
